services:
  - type: web
    name: server1
    env: node
    plan: free
    rootDir: my-proxy-server
    buildCommand: |
      npm ci
      ls -la node_modules/ipaddr.js || (echo "ipaddr.js missing" && exit 1)
    startCommand: node server1.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_FUND
        value: "false"

  - type: web
    name: analytics-server
    env: node
    plan: free
    rootDir: my-proxy-server
    buildCommand: |
      npm ci
      ls -la node_modules/ipaddr.js || (echo "ipaddr.js missing" && exit 1)
    startCommand: node analytics_server.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_FUND
        value: "false"
